services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "ld50"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  server:
    image: golang
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./:/server
    ports:
      - "8090:8090"
    command: sh -c "cd /server && go run ."

volumes:
  postgres-data: